
import type { Metadata } from "next";
import { Tektur, Electrolize, Alexandria, Tajawal } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { LanguageProvider } from "@/providers/LanguageProvider";
import { cookies } from "next/headers";
import { Language } from "@/hooks/Language";


// English fonts
const tektur = Tektur({
  variable: "--font-heading-en",
  weight: "400",
  subsets: ["latin"],
});

const electrolize = Electrolize({
  variable: "--font-default-en",
  weight: "400",
  subsets: ["latin"],
});

// Arabic fonts
const alexandria = Alexandria({
  variable: "--font-heading-ar",
  weight: ["400", "700"],
  subsets: ["arabic"],
});

const tajawal = Tajawal({
  variable: "--font-default-ar",
  weight: ["400", "700"],
  subsets: ["arabic"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const lang: Language = cookieStore.get("language")?.value as Language || "en";


  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"} suppressHydrationWarning className={`${tektur.variable} ${electrolize.variable} ${alexandria.variable} ${tajawal.variable}`}>
      <body className="antialiased">
        <LanguageProvider initialLang={lang}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}