'use client'
import type { Metadata } from "next";
import { Tektur, Electrolize, Alexandria, Tajawal } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { useLanguage } from "@/hooks/Language";

// English fonts
const tektur = Tektur({
  variable: "--font-heading-en",
  weight: "400",
  subsets: ["latin"],
});

const electrolize = Electrolize({
  variable: "--font-default-en",
  weight: "400",
  subsets: ["latin"],
});

// Arabic fonts
const alexandria = Alexandria({
  variable: "--font-heading-ar",
  weight: ["400", "700"],
  subsets: ["arabic"],
});

const tajawal = Tajawal({
  variable: "--font-default-ar",
  weight: ["400", "700"],
  subsets: ["arabic"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { direction, lang } = useLanguage();
  return (
    <html lang={lang} dir={direction} suppressHydrationWarning className={`${tektur.variable} ${electrolize.variable} ${alexandria.variable} ${tajawal.variable}`}>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}